from criteres import *

# ic_criteria()
liste = truth_table()
print("\n")
print_truth_table(liste)
print("--------------------------------------------- \n")
print("--------------------------------------------- \n")
cacc_criteria(liste)
print("--------------------------------------------- \n")
print("--------------------------------------------- \n")
gicc_criteria(liste)
print("--------------------------------------------- \n")
print("--------------------------------------------- \n")
ic_criteria()